### ISSUE TITLE
mainxx程序会被终止

### ISSUE THREAD

**Issue by Peterist** [kagaya85/MPI_Convolution#1]
你好，在执行main和mainx程序时没有问题但是执行mainxx时会遇到crt detected that the application wrote to memory after end of heap buffer的提示，最终result.bmp变成了黑色，请问大概是什么原因呢？

**Comment by kagaya85** [comment]
你好，推断应该是代码中存在的bug导致内存泄漏的问题（如数组越界），导致delete内存的时候线程崩溃没有计算出最后的结果。

可以尝试一下yyy.cpp中的代码，这个是我们当时测试中效果最好的

**Comment by Peterist** [comment]
谢谢回复，yyy.cpp代码在执行会有error C2039: “count”: 不是“MPI_Status”的成员；error C2660: “memcpy”: 函数不接受 2 个参数这两个报错，经过查找好像mpi_status确实没有count成员错误来源句：
for (source = 1; source < size; source++)
        {
            MPI_Recv(resBuf, BmpWidth * 3 * BmpHeight, MPI_UNSIGNED_CHAR, MPI_ANY_SOURCE, 99, MPI_COMM_WORLD, &status);
            if (status.MPI_SOURCE != size - 1)
                memcpy(result + status.MPI_SOURCE * BmpHeight / size * BmpWidth * 3, resBuf, status.count);
            else
                memcpy(result + status.MPI_SOURCE * BmpHeight / size * BmpWidth * 3, resBuf, status.count);
        }
该段if和else语句内容相同，是不是这一段搞错了？
将status.count改成常数执行后在多进程中会发现最终图片final.bmp只有最下面的部分，如2进程只有下面1/2，3进程只有下面1/3

**Comment by kagaya85** [comment]
查阅资料后估计是mpi版本的问题，open-mpi v4可能移除了count，可以尝试其他的MPI版本，应该是包含count这个字段，参考[微软的文档](https://docs.microsoft.com/en-us/message-passing-interface/mpi-status-structure)和其他版本的[mpi.h](https://quark.phy.bnl.gov/~creutz/qcdoc/mpi/mpi.h)

如果是open-mpi的话获取count可以使用MPI_Get_count这个方法，参考[这里](https://stackoverflow.com/questions/4831628/unknown-field-in-mpi-status)

**Comment by Peterist** [comment]
用MPI_Get_count成功解决了问题，语句修改为如下
int number;
for (source = 1; source < size; source++){
      MPI_Recv(resBuf, BmpWidth * 3 * BmpHeight, MPI_UNSIGNED_CHAR, MPI_ANY_SOURCE, 99, MPI_COMM_WORLD, &status);
      if (status.MPI_SOURCE != size - 1) {
	   MPI_Get_count(&status, MPI_UNSIGNED_CHAR, &number);
           memcpy(result + status.MPI_SOURCE * BmpHeight / size * BmpWidth * 3, resBuf, number);
       }
       else {
	       MPI_Get_count(&status, MPI_UNSIGNED_CHAR, &number);
	       memcpy(result + status.MPI_SOURCE * BmpHeight / size * BmpWidth * 3, resBuf, number);
		}	
	}
谢谢！！！

**Comment by kagaya85** [comment]
好的，也欢迎提pr帮助修改👏
